# **HANDS-ON 5: Criando um Modelo Simplificado de Camadas - Dense Layer**

Até agora utilizamos o que é chamado de camadas totalmente conectadas. Em inglês, a terminologia para essas camadas na programação e em artigos é "Dense". Como demonstrado no site da biblioteca Keras:

```
Dense implementa a operação: output = activation(dot(input, kernel) + bias) onde ativação é a função de ativação por elemento passada como argumento de ativação, kernel é uma matriz de pesos criada pela camada e bias é um vetor de bias criado pela camada (aplicável apenas se use_bias for True). Estes são todos os atributos de Densos.
```

Iremos utilizar como base a seguinte arquitetura:

In [1]:
import numpy as np

# Criando uma vlasse de camadas de neruônios do tipo totalmente conectados "Dense".
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
    # inicializa os pesos e bias com valores aleatorios
        pass

    # Forward pass
    def forward(self, inputs):
    # Calcula o valor de saida com base nos inputs, pesos e bias.
        pass 

Iremos utilizar pesos aleatórios para cada camada. Isso ajuda na função passo - fazendo com que haja que uma convergencia para o modelo. Um problema muito famoso anteriormente surgiu quando todos os neurônios tinhamseus pesos inciados em zero. Acontecia que o modelo fazia exatamente os mesmos cálculos em todas as camadas e, consequentemente, não havia aprendizado - é devido a esse motivo que as redes neurais "quebram a simetria" de pesos e possuem uma capacidade de aprender. Também é possível utilizar pesos e bias especificos para cada camada, mas, nesse caso, o modelo já teria que ter treinando com dados anteriormente para que os valores de pesos e bias fossem estabelecidos.

In [2]:
import numpy as np

# Criando uma vlasse de camadas de neruônios do tipo totalmente conectados "Dense".
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = np.random.randn(n_inputs, n_neurons) * 0.1
        self.biases = np.zeros((1, n_neurons))

    # Forward pass
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        return self.output

### **Fazendo uma breve demonstração da classe que estamos criando:**

In [3]:
# Gerando uma camada de neurônios e observando seus pesos e biases.

camada_demonstracao = Layer_Dense(3, 3)  # Uma cada de 3 entradas e 3 neurônios.
print(f'Pesos da camada 1:\n{camada_demonstracao.weights}\n')
print(f'Biases da camada 1:\n{camada_demonstracao.biases}\n')

# OBS: Note que toda ve que iniciamos esse código, os pesos são gerados aleatoriamente.

Pesos da camada 1:
[[-0.10932781 -0.11593294  0.03556925]
 [ 0.0187206  -0.21949212 -0.10157492]
 [-0.09322372 -0.1217249  -0.02458365]]

Biases da camada 1:
[[0. 0. 0.]]



Vamos agora realizar um teste de entrada com inputs:

In [4]:
inputs = [[1, 2, 3],
          [4, 5, 6]]

camada_01 = Layer_Dense(3, 3)
camada_01.forward(inputs)


array([[-0.3696385 ,  0.1468098 ,  0.40550314],
       [-0.78380178,  0.30550421,  0.96411677]])

## **Classes de Ativações.**

Como vimos no Hands-On passado, existem diversas formas de ativações. Iremos criar as classes para algumas funções de ativação e implementar elas em nossos modelos.

In [5]:
import numpy as np

# Ativação ReLU 
class Activation_ReLU:
    def forward(self, inputs):
        # Calcula o valor de saida
        self.output = np.maximum(0, inputs)

# Ativação Softmax
class Activation_Softmax:
    def forward(self, inputs):
        # Obtém probabilidades não normalizadas
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        # Normaliza para cada amostra
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

## **Modelo de camadas com funções de ativação**

In [7]:
import random as rd

batch_inputs = [[rd.random() for i in range(4)],
                [rd.random() for i in range(4)],
                [rd.random() for i in range(4)]]


camada_01 = Layer_Dense(4, 4)
activation_01 = Activation_ReLU()

camada_02 = Layer_Dense(4, 4)
activation_02 = Activation_Softmax()

camada_01.forward(batch_inputs)
activation_01.forward(camada_01.output)
camada_02.forward(activation_01.output)
activation_02.forward(camada_02.output)

print(f'Camada 1: \n{camada_01.output}\n')
print(f'Camada 2: \n{camada_02.output}')


Camada 1: 
[[ 0.04697085  0.03786358 -0.0541443  -0.05833209]
 [ 0.06390732  0.12632154 -0.05764834 -0.00689434]
 [ 0.12192485  0.11595497 -0.11152636 -0.24515042]]

Camada 2: 
[[-0.00722061 -0.00298639  0.01114767 -0.00323407]
 [-0.01579991  0.00364779  0.03138375 -0.00473809]
 [-0.02015452 -0.00593046  0.03276727 -0.00847467]]
